  ### Kafka UI
  ankey-kafka-ui${NUM}:
    image: nexus.da.lan:8444/provectuslabs/kafka-ui
    container_name: ankey-kafka-ui${NUM}
    ports:
      - "${PORT_KAFKA_UI}:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka${NUM}:${PORT_KAFKA}
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_PLAINTEXT
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: SCRAM-SHA-256
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: >-
        org.apache.kafka.common.security.scram.ScramLoginModule required username="messageLogin" password="messagePassword";
    networks:
      - ankey-network
