  ### Kafka UI
  ankey-kafka-ui${NUM}:
    image: nexus.da.lan:8444/provectuslabs/kafka-ui
    container_name: ankey-kafka-ui${NUM}
    ports:
      - "${PORT_KAFKA_UI}:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka${NUM}:9092
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: PLAINTEXT
    networks:
      - ankey-network
