  ### Ankey Core
  ankey${NUM}:
    container_name: ankey${NUM}
    build:
      context: ./docker
      dockerfile: Dockerfile-ankey
    volumes:
      - "./ankey:/opt/ankey"
    ports:
      - "${PORT_HTTP}:8080"
      - "${PORT_DEBUG}:5005"
      - "${PORT_JMX}:9010"
    environment:
      ANKEYIDM_OPTS: "-Xmx1G -Xms1G -Xverify:none -XX:+AggressiveOpts -Djava.net.preferIPv4Stack=true -XX:+UseG1GC"
      LOGGING_CONFIG: "-Dlogback.configurationFile=/opt/ankey/logger/logback.xml"
      ANKEYIDM_ELASTIC_HOST: opensearch${NUM}
      ANKEYIDM_ELASTIC_PORT: 9200
      ANKEYIDM_PG_URL: postgres${NUM}:5432
      ANKEYIDM_KAFKA_HOST: kafka${NUM}:9092
      HARDWARE_ID: teamcity
      JPDA_SUSPEND: n
    depends_on:
      opensearch${NUM}:
        condition: service_started
      postgres${NUM}:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "--header", "Accept: application/json", "--header", "X-Ankey-Username: ankey", "--header", "X-Ankey-Password: ankey", "http://localhost:${PORT_HTTP}/ankey/info/login" ]
      interval: 1m
      timeout: 30s
      retries: 10
      start_period: 2m
    networks:
      - ankey-network